// AUTO-GENERATED by scripts/n400/build-oral-config.ts — do not edit by hand.
// Regenerate: npx tsx scripts/n400/build-oral-config.ts (from apps/website)
// Spec: docs/superpowers/specs/2026-09-24-n400-civics-oral-answers-design.md §3.1

import type { OralAnswerConfig } from './types';

export const ORAL_ANSWER_CONFIG: Record<number, OralAnswerConfig> = {
  "1": {
    "type": "single",
    "alternatives": [
      [
        "republic"
      ]
    ]
  },
  "2": {
    "type": "single",
    "alternatives": [
      [
        "constitution"
      ]
    ]
  },
  "3": {
    "type": "single",
    "alternatives": [
      [
        "forms government"
      ]
    ]
  },
  "4": {
    "type": "single",
    "alternatives": [
      [
        "self government"
      ]
    ]
  },
  "5": {
    "type": "single",
    "alternatives": [
      [
        "amendments"
      ]
    ]
  },
  "6": {
    "type": "single",
    "alternatives": [
      [
        "rights"
      ]
    ]
  },
  "7": {
    "type": "single",
    "alternatives": [
      [
        "27"
      ]
    ]
  },
  "8": {
    "type": "phrase",
    "alternatives": [
      [
        "all people created equal"
      ]
    ],
    "minKeywords": 3
  },
  "9": {
    "type": "single",
    "alternatives": [
      [
        "declaration independence"
      ]
    ]
  },
  "10": {
    "type": "enumeration",
    "alternatives": [
      [
        "liberty",
        "equality"
      ]
    ]
  },
  "11": {
    "type": "single",
    "alternatives": [
      [
        "declaration independence"
      ]
    ]
  },
  "12": {
    "type": "single",
    "alternatives": [
      [
        "capitalism"
      ]
    ]
  },
  "13": {
    "type": "single",
    "alternatives": [
      [
        "everyone follow"
      ]
    ]
  },
  "14": {
    "type": "single",
    "alternatives": [
      [
        "declaration independence"
      ]
    ]
  },
  "15": {
    "type": "single",
    "alternatives": [
      [
        "checks balances"
      ]
    ]
  },
  "16": {
    "type": "enumeration",
    "alternatives": [
      [
        "congress",
        "president",
        "courts"
      ]
    ]
  },
  "17": {
    "type": "single",
    "alternatives": [
      [
        "executive"
      ]
    ]
  },
  "18": {
    "type": "single",
    "alternatives": [
      [
        "congress"
      ]
    ]
  },
  "19": {
    "type": "enumeration",
    "alternatives": [
      [
        "senate",
        "house representatives"
      ]
    ]
  },
  "20": {
    "type": "single",
    "alternatives": [
      [
        "writes laws"
      ]
    ]
  },
  "21": {
    "type": "single",
    "alternatives": [
      [
        "100"
      ]
    ]
  },
  "22": {
    "type": "single",
    "alternatives": [
      [
        "6 years"
      ]
    ]
  },
  "24": {
    "type": "single",
    "alternatives": [
      [
        "435"
      ]
    ]
  },
  "25": {
    "type": "single",
    "alternatives": [
      [
        "2 years"
      ]
    ]
  },
  "26": {
    "type": "phrase",
    "alternatives": [
      [
        "more closely follow public opinion"
      ]
    ],
    "minKeywords": 4
  },
  "27": {
    "type": "single",
    "alternatives": [
      [
        "2"
      ]
    ]
  },
  "28": {
    "type": "single",
    "alternatives": [
      [
        "equal representation"
      ]
    ]
  },
  "30": {
    "type": "single",
    "alternatives": [
      [
        "johnson"
      ]
    ]
  },
  "31": {
    "type": "single",
    "alternatives": [
      [
        "citizens state"
      ]
    ]
  },
  "32": {
    "type": "single",
    "alternatives": [
      [
        "citizens state"
      ]
    ]
  },
  "33": {
    "type": "single",
    "alternatives": [
      [
        "citizens district"
      ]
    ]
  },
  "34": {
    "type": "single",
    "alternatives": [
      [
        "citizens district"
      ]
    ]
  },
  "35": {
    "type": "single",
    "alternatives": [
      [
        "people"
      ]
    ]
  },
  "36": {
    "type": "single",
    "alternatives": [
      [
        "4"
      ]
    ]
  },
  "37": {
    "type": "single",
    "alternatives": [
      [
        "keep powerful"
      ]
    ]
  },
  "38": {
    "type": "single",
    "alternatives": [
      [
        "trump"
      ]
    ]
  },
  "39": {
    "type": "single",
    "alternatives": [
      [
        "vance"
      ]
    ]
  },
  "40": {
    "type": "single",
    "alternatives": [
      [
        "vice"
      ]
    ]
  },
  "41": {
    "type": "single",
    "alternatives": [
      [
        "signs bills laws"
      ]
    ]
  },
  "42": {
    "type": "single",
    "alternatives": [
      [
        "president"
      ]
    ],
    "mustExclude": [
      "vice"
    ]
  },
  "43": {
    "type": "single",
    "alternatives": [
      [
        "president"
      ]
    ],
    "mustExclude": [
      "vice"
    ]
  },
  "44": {
    "type": "single",
    "alternatives": [
      [
        "president"
      ]
    ],
    "mustExclude": [
      "vice"
    ]
  },
  "45": {
    "type": "single",
    "alternatives": [
      [
        "president"
      ]
    ],
    "mustExclude": [
      "vice"
    ]
  },
  "46": {
    "type": "single",
    "alternatives": [
      [
        "president"
      ]
    ],
    "mustExclude": [
      "vice"
    ]
  },
  "47": {
    "type": "single",
    "alternatives": [
      [
        "advises"
      ]
    ]
  },
  "48": {
    "type": "enumeration",
    "alternatives": [
      [
        "secretary education",
        "secretary energy"
      ]
    ]
  },
  "49": {
    "type": "single",
    "alternatives": [
      [
        "decides elected president"
      ]
    ]
  },
  "50": {
    "type": "single",
    "alternatives": [
      [
        "supreme court"
      ]
    ]
  },
  "51": {
    "type": "single",
    "alternatives": [
      [
        "reviews laws"
      ]
    ]
  },
  "52": {
    "type": "single",
    "alternatives": [
      [
        "supreme"
      ]
    ]
  },
  "53": {
    "type": "single",
    "alternatives": [
      [
        "9"
      ]
    ]
  },
  "54": {
    "type": "single",
    "alternatives": [
      [
        "5"
      ]
    ]
  },
  "55": {
    "type": "single",
    "alternatives": [
      [
        "life"
      ]
    ]
  },
  "56": {
    "type": "single",
    "alternatives": [
      [
        "independent"
      ]
    ]
  },
  "57": {
    "type": "single",
    "alternatives": [
      [
        "roberts"
      ]
    ]
  },
  "58": {
    "type": "single",
    "alternatives": [
      [
        "print paper money"
      ]
    ]
  },
  "59": {
    "type": "single",
    "alternatives": [
      [
        "give driver license"
      ]
    ]
  },
  "60": {
    "type": "phrase",
    "alternatives": [
      [
        "powers not given federal government belong states"
      ]
    ],
    "minKeywords": 5,
    "mustInclude": [
      "not"
    ]
  },
  "63": {
    "type": "single",
    "alternatives": [
      [
        "citizen"
      ]
    ]
  },
  "64": {
    "type": "single",
    "alternatives": [
      [
        "citizens"
      ]
    ]
  },
  "65": {
    "type": "enumeration",
    "alternatives": [
      [
        "freedom speech",
        "freedom religion",
        "bear arms"
      ]
    ]
  },
  "66": {
    "type": "single",
    "alternatives": [
      [
        "united states"
      ]
    ]
  },
  "67": {
    "type": "enumeration",
    "alternatives": [
      [
        "obey laws",
        "loyal"
      ]
    ]
  },
  "68": {
    "type": "single",
    "alternatives": [
      [
        "naturalize"
      ]
    ]
  },
  "69": {
    "type": "enumeration",
    "alternatives": [
      [
        "vote",
        "write newspaper"
      ]
    ]
  },
  "70": {
    "type": "single",
    "alternatives": [
      [
        "vote"
      ]
    ]
  },
  "71": {
    "type": "single",
    "alternatives": [
      [
        "required law"
      ]
    ]
  },
  "72": {
    "type": "single",
    "alternatives": [
      [
        "required law"
      ]
    ]
  },
  "73": {
    "type": "single",
    "alternatives": [
      [
        "freedom"
      ]
    ]
  },
  "74": {
    "type": "single",
    "alternatives": [
      [
        "native"
      ]
    ]
  },
  "75": {
    "type": "single",
    "alternatives": [
      [
        "africans"
      ]
    ]
  },
  "76": {
    "type": "single",
    "alternatives": [
      [
        "war independence"
      ]
    ]
  },
  "77": {
    "type": "single",
    "alternatives": [
      [
        "high taxes"
      ]
    ]
  },
  "78": {
    "type": "single",
    "alternatives": [
      [
        "jefferson"
      ]
    ]
  },
  "79": {
    "type": "single",
    "alternatives": [
      [
        "july 4 1776"
      ]
    ]
  },
  "80": {
    "type": "single",
    "alternatives": [
      [
        "declaration independence"
      ]
    ]
  },
  "81": {
    "type": "enumeration",
    "alternatives": [
      [
        "new york",
        "new jersey",
        "north carolina",
        "south carolina",
        "virginia"
      ]
    ]
  },
  "82": {
    "type": "single",
    "alternatives": [
      [
        "constitution"
      ]
    ]
  },
  "83": {
    "type": "single",
    "alternatives": [
      [
        "jay"
      ]
    ]
  },
  "84": {
    "type": "phrase",
    "alternatives": [
      [
        "helped people understand constitution"
      ]
    ],
    "minKeywords": 3
  },
  "85": {
    "type": "single",
    "alternatives": [
      [
        "inventor"
      ]
    ]
  },
  "86": {
    "type": "single",
    "alternatives": [
      [
        "father country"
      ]
    ]
  },
  "87": {
    "type": "single",
    "alternatives": [
      [
        "writer declaration independence"
      ]
    ]
  },
  "88": {
    "type": "single",
    "alternatives": [
      [
        "father constitution"
      ]
    ]
  },
  "89": {
    "type": "single",
    "alternatives": [
      [
        "secretary treasury"
      ]
    ]
  },
  "90": {
    "type": "single",
    "alternatives": [
      [
        "louisiana"
      ]
    ]
  },
  "91": {
    "type": "single",
    "alternatives": [
      [
        "civil"
      ]
    ]
  },
  "92": {
    "type": "single",
    "alternatives": [
      [
        "civil"
      ]
    ]
  },
  "93": {
    "type": "single",
    "alternatives": [
      [
        "lincoln assassinated"
      ]
    ]
  },
  "94": {
    "type": "single",
    "alternatives": [
      [
        "freed slaves"
      ]
    ]
  },
  "95": {
    "type": "single",
    "alternatives": [
      [
        "freed slaves"
      ]
    ]
  },
  "96": {
    "type": "single",
    "alternatives": [
      [
        "civil"
      ]
    ]
  },
  "97": {
    "type": "single",
    "alternatives": [
      [
        "14"
      ]
    ]
  },
  "98": {
    "type": "single",
    "alternatives": [
      [
        "after civil war"
      ]
    ]
  },
  "99": {
    "type": "single",
    "alternatives": [
      [
        "stone"
      ]
    ]
  },
  "100": {
    "type": "single",
    "alternatives": [
      [
        "vietnam"
      ]
    ]
  },
  "101": {
    "type": "single",
    "alternatives": [
      [
        "support allied powers"
      ]
    ]
  },
  "102": {
    "type": "phrase",
    "alternatives": [
      [
        "after world war 1"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "1"
    ]
  },
  "103": {
    "type": "phrase",
    "alternatives": [
      [
        "longest economic recession modern history"
      ]
    ],
    "minKeywords": 4
  },
  "104": {
    "type": "phrase",
    "alternatives": [
      [
        "stock market crash 1929"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "1929"
    ]
  },
  "105": {
    "type": "single",
    "alternatives": [
      [
        "roosevelt"
      ]
    ]
  },
  "106": {
    "type": "phrase",
    "alternatives": [
      [
        "japanese attacked pearl harbor"
      ]
    ],
    "minKeywords": 3
  },
  "107": {
    "type": "phrase",
    "alternatives": [
      [
        "general world war 2"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "2"
    ]
  },
  "108": {
    "type": "single",
    "alternatives": [
      [
        "russia"
      ]
    ]
  },
  "109": {
    "type": "single",
    "alternatives": [
      [
        "communism"
      ]
    ]
  },
  "110": {
    "type": "single",
    "alternatives": [
      [
        "stop spread communism"
      ]
    ]
  },
  "111": {
    "type": "single",
    "alternatives": [
      [
        "stop spread communism"
      ]
    ]
  },
  "112": {
    "type": "phrase",
    "alternatives": [
      [
        "fought end racial discrimination"
      ]
    ],
    "minKeywords": 3
  },
  "113": {
    "type": "single",
    "alternatives": [
      [
        "fought civil rights"
      ]
    ]
  },
  "114": {
    "type": "phrase",
    "alternatives": [
      [
        "force iraqi military kuwait"
      ]
    ],
    "minKeywords": 3
  },
  "115": {
    "type": "single",
    "alternatives": [
      [
        "terrorists attacked"
      ]
    ]
  },
  "116": {
    "type": "single",
    "alternatives": [
      [
        "war iraq"
      ]
    ]
  },
  "117": {
    "type": "single",
    "alternatives": [
      [
        "crow"
      ]
    ]
  },
  "118": {
    "type": "single",
    "alternatives": [
      [
        "airplane"
      ]
    ]
  },
  "119": {
    "type": "single",
    "alternatives": [
      [
        "washington"
      ]
    ]
  },
  "120": {
    "type": "single",
    "alternatives": [
      [
        "new york"
      ]
    ]
  },
  "121": {
    "type": "single",
    "alternatives": [
      [
        "original colonies"
      ]
    ]
  },
  "122": {
    "type": "single",
    "alternatives": [
      [
        "states"
      ]
    ]
  },
  "123": {
    "type": "single",
    "alternatives": [
      [
        "star spangled banner"
      ]
    ]
  },
  "124": {
    "type": "single",
    "alternatives": [
      [
        "all become"
      ]
    ]
  },
  "125": {
    "type": "single",
    "alternatives": [
      [
        "country birthday"
      ]
    ]
  },
  "126": {
    "type": "enumeration",
    "alternatives": [
      [
        "new year",
        "thanksgiving",
        "christmas"
      ]
    ]
  },
  "127": {
    "type": "phrase",
    "alternatives": [
      [
        "holiday honor soldiers died military service"
      ]
    ],
    "minKeywords": 4
  },
  "128": {
    "type": "single",
    "alternatives": [
      [
        "honor people military"
      ]
    ]
  }
};
