// AUTO-GENERATED by scripts/n400/build-whatmean-oral-config.ts — do not edit by hand.
// Regenerate: npx tsx scripts/n400/build-whatmean-oral-config.ts (from apps/website)
// Spec: docs/superpowers/specs/2026-09-25-n400-speaking-oral-answers-design.md §3.1

import type { OralAnswerConfig } from './types';

export const WHATMEAN_ORAL_CONFIG: Record<string, OralAnswerConfig> = {
  "wm-1": {
    "type": "single",
    "alternatives": [
      [
        "say citizen"
      ]
    ]
  },
  "wm-2": {
    "type": "phrase",
    "alternatives": [
      [
        "sign up choose leader"
      ]
    ],
    "minKeywords": 3
  },
  "wm-3": {
    "type": "single",
    "alternatives": [
      [
        "choose leader election"
      ]
    ]
  },
  "wm-4": {
    "type": "phrase",
    "alternatives": [
      [
        "not pay taxes time"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "not"
    ]
  },
  "wm-5": {
    "type": "single",
    "alternatives": [
      [
        "not live"
      ]
    ]
  },
  "wm-6": {
    "type": "single",
    "alternatives": [
      [
        "not citizen"
      ]
    ]
  },
  "wm-7": {
    "type": "single",
    "alternatives": [
      [
        "remove government force"
      ]
    ]
  },
  "wm-8": {
    "type": "single",
    "alternatives": [
      [
        "against constitution"
      ]
    ]
  },
  "wm-9": {
    "type": "single",
    "alternatives": [
      [
        "knife"
      ],
      [
        "gun"
      ]
    ]
  },
  "wm-10": {
    "type": "phrase",
    "alternatives": [
      [
        "cause great pain someone"
      ]
    ],
    "minKeywords": 3
  },
  "wm-11": {
    "type": "phrase",
    "alternatives": [
      [
        "kill group people religion race"
      ]
    ],
    "minKeywords": 4
  },
  "wm-12": {
    "type": "single",
    "alternatives": [
      [
        "cause someone die"
      ]
    ]
  },
  "wm-13": {
    "type": "phrase",
    "alternatives": [
      [
        "place police keep people arrested"
      ]
    ],
    "minKeywords": 4
  },
  "wm-14": {
    "type": "phrase",
    "alternatives": [
      [
        "place people forced stay"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "stay"
    ]
  },
  "wm-15": {
    "type": "phrase",
    "alternatives": [
      [
        "place people forced work"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "work"
    ]
  },
  "wm-16": {
    "type": "single",
    "alternatives": [
      [
        "action breaks law"
      ]
    ]
  },
  "wm-17": {
    "type": "single",
    "alternatives": [
      [
        "minor crime"
      ]
    ]
  },
  "wm-18": {
    "type": "single",
    "alternatives": [
      [
        "caught police"
      ]
    ]
  },
  "wm-19": {
    "type": "single",
    "alternatives": [
      [
        "given ticket police"
      ]
    ]
  },
  "wm-20": {
    "type": "single",
    "alternatives": [
      [
        "jailed police"
      ]
    ]
  },
  "wm-21": {
    "type": "single",
    "alternatives": [
      [
        "sex money"
      ]
    ]
  },
  "wm-22": {
    "type": "phrase",
    "alternatives": [
      [
        "bring something illegally country"
      ]
    ],
    "minKeywords": 3
  },
  "wm-23": {
    "type": "single",
    "alternatives": [
      [
        "illegal drugs"
      ]
    ],
    "mustExclude": [
      "equipment",
      "tools"
    ]
  },
  "wm-24": {
    "type": "phrase",
    "alternatives": [
      [
        "equipment make use illegal drugs"
      ]
    ],
    "minKeywords": 4
  },
  "wm-25": {
    "type": "phrase",
    "alternatives": [
      [
        "gain things green card"
      ]
    ],
    "minKeywords": 3
  },
  "wm-26": {
    "type": "phrase",
    "alternatives": [
      [
        "play game money against law"
      ]
    ],
    "minKeywords": 4
  },
  "wm-27": {
    "type": "single",
    "alternatives": [
      [
        "pay child support"
      ]
    ]
  },
  "wm-28": {
    "type": "phrase",
    "alternatives": [
      [
        "give money ex spouse after divorce"
      ]
    ],
    "minKeywords": 4
  },
  "wm-29": {
    "type": "single",
    "alternatives": [
      [
        "lie"
      ],
      [
        "lying"
      ]
    ]
  },
  "wm-30": {
    "type": "single",
    "alternatives": [
      [
        "money government"
      ]
    ]
  },
  "wm-31": {
    "type": "phrase",
    "alternatives": [
      [
        "claim something not true"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "not"
    ]
  },
  "wm-32": {
    "type": "phrase",
    "alternatives": [
      [
        "say things not true"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "not"
    ]
  },
  "wm-33": {
    "type": "single",
    "alternatives": [
      [
        "forced leave"
      ]
    ]
  },
  "wm-34": {
    "type": "single",
    "alternatives": [
      [
        "supreme law land"
      ]
    ]
  },
  "wm-35": {
    "type": "single",
    "alternatives": [
      [
        "republic"
      ]
    ]
  },
  "wm-36": {
    "type": "single",
    "alternatives": [
      [
        "promise loyal"
      ]
    ]
  },
  "wm-37": {
    "type": "phrase",
    "alternatives": [
      [
        "use gun defend war"
      ]
    ],
    "minKeywords": 3,
    "mustExclude": [
      "not"
    ]
  },
  "wm-38": {
    "type": "phrase",
    "alternatives": [
      [
        "work not fighting war"
      ]
    ],
    "minKeywords": 3,
    "mustInclude": [
      "not"
    ]
  },
  "wm-39": {
    "type": "single",
    "alternatives": [
      [
        "nursing"
      ],
      [
        "cooking"
      ],
      [
        "translation"
      ]
    ]
  },
  "wm-40": {
    "type": "single",
    "alternatives": [
      [
        "not military"
      ],
      [
        "not soldier"
      ]
    ]
  },
  "wm-41": {
    "type": "phrase",
    "alternatives": [
      [
        "non military work national crisis"
      ]
    ],
    "minKeywords": 4
  },
  "wm-42": {
    "type": "single",
    "alternatives": [
      [
        "red cross"
      ]
    ]
  },
  "wm-43": {
    "type": "single",
    "alternatives": [
      [
        "drink much alcohol"
      ],
      [
        "drink alcohol regularly"
      ],
      [
        "alcoholic"
      ]
    ]
  },
  "wm-44": {
    "type": "phrase",
    "alternatives": [
      [
        "married more 1 person same time"
      ]
    ],
    "minKeywords": 4,
    "mustInclude": [
      "1"
    ]
  },
  "wm-45": {
    "type": "phrase",
    "alternatives": [
      [
        "single married divorced widowed"
      ]
    ],
    "minKeywords": 2
  },
  "wm-46": {
    "type": "single",
    "alternatives": [
      [
        "husband"
      ],
      [
        "wife"
      ]
    ]
  },
  "wm-47": {
    "type": "phrase",
    "alternatives": [
      [
        "marriage officially ended never happened"
      ]
    ],
    "minKeywords": 4,
    "mustInclude": [
      "never"
    ]
  },
  "wm-48": {
    "type": "single",
    "alternatives": [
      [
        "lie under oath"
      ]
    ]
  },
  "wm-49": {
    "type": "single",
    "alternatives": [
      [
        "promise tell truth"
      ]
    ]
  },
  "wm-50": {
    "type": "single",
    "alternatives": [
      [
        "prove something true"
      ]
    ]
  },
  "wm-51": {
    "type": "single",
    "alternatives": [
      [
        "not decided"
      ]
    ]
  },
  "wm-52": {
    "type": "single",
    "alternatives": [
      [
        "not something"
      ]
    ],
    "mustInclude": [
      "not"
    ],
    "mustExclude": [
      "true"
    ]
  },
  "wm-53": {
    "type": "phrase",
    "alternatives": [
      [
        "army not work official government"
      ]
    ],
    "minKeywords": 4,
    "mustInclude": [
      "not"
    ]
  },
  "wm-54": {
    "type": "phrase",
    "alternatives": [
      [
        "group uses weapons fight government"
      ]
    ],
    "minKeywords": 4
  },
  "wm-55": {
    "type": "phrase",
    "alternatives": [
      [
        "group acts police not official"
      ]
    ],
    "minKeywords": 4,
    "mustInclude": [
      "not"
    ]
  },
  "wm-56": {
    "type": "phrase",
    "alternatives": [
      [
        "punishment decided law instead jail time"
      ]
    ],
    "minKeywords": 4
  },
  "wm-57": {
    "type": "phrase",
    "alternatives": [
      [
        "program help someone recover drugs alcohol"
      ]
    ],
    "minKeywords": 4
  },
  "wm-58": {
    "type": "phrase",
    "alternatives": [
      [
        "good person following law"
      ]
    ],
    "minKeywords": 3
  },
  "wm-59": {
    "type": "single",
    "alternatives": [
      [
        "become citizen"
      ]
    ]
  },
  "wm-60": {
    "type": "single",
    "alternatives": [
      [
        "before"
      ]
    ]
  },
  "wm-61": {
    "type": "single",
    "alternatives": [
      [
        "right now"
      ],
      [
        "live now"
      ]
    ]
  },
  "wm-62": {
    "type": "single",
    "alternatives": [
      [
        "tell"
      ],
      [
        "provide information"
      ]
    ]
  }
};
