// Regenerates src/lib/n400/oral/whatmean-oral-config.generated.ts.
// Run from apps/website: npx tsx scripts/n400/build-whatmean-oral-config.ts
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildAllWhatMeanOralConfigs } from '../../src/lib/n400/oral/build-whatmean-config';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../src/lib/n400/oral/whatmean-oral-config.generated.ts');

const body =
  '// AUTO-GENERATED by scripts/n400/build-whatmean-oral-config.ts — do not edit by hand.\n' +
  '// Regenerate: npx tsx scripts/n400/build-whatmean-oral-config.ts (from apps/website)\n' +
  '// Spec: docs/superpowers/specs/2026-09-25-n400-speaking-oral-answers-design.md §3.1\n\n' +
  "import type { OralAnswerConfig } from './types';\n\n" +
  `export const WHATMEAN_ORAL_CONFIG: Record<string, OralAnswerConfig> = ${JSON.stringify(buildAllWhatMeanOralConfigs(), null, 2)};\n`;

writeFileSync(out, body);
console.log(`wrote ${out}`);
