// Regenerates src/lib/n400/oral/oral-answer-config.generated.ts.
// Run from apps/website: npx tsx scripts/n400/build-oral-config.ts
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildAllOralConfigs } from '../../src/lib/n400/oral/build-config';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../src/lib/n400/oral/oral-answer-config.generated.ts');

const body =
  '// AUTO-GENERATED by scripts/n400/build-oral-config.ts — do not edit by hand.\n' +
  '// Regenerate: npx tsx scripts/n400/build-oral-config.ts (from apps/website)\n' +
  '// Spec: docs/superpowers/specs/2026-09-24-n400-civics-oral-answers-design.md §3.1\n\n' +
  "import type { OralAnswerConfig } from './types';\n\n" +
  `export const ORAL_ANSWER_CONFIG: Record<number, OralAnswerConfig> = ${JSON.stringify(buildAllOralConfigs(), null, 2)};\n`;

writeFileSync(out, body);
console.log(`wrote ${out}`);
