-- N400 distractors (manually authored, civics-knowledge plausible).
-- Q29 has 5 fictional Member-of-Congress placeholders; the correct answer is injected from n400_representatives at runtime.
-- display_order >= 100 to avoid clashing with seeded correct answers (which start at 0).

INSERT INTO public.n400_answers (question_id, answer_en, answer_vi, is_correct, display_order) VALUES
  (1, 'Monarchy', 'Quân chủ', false, 100),
  (1, 'Direct democracy', 'Dân chủ trực tiếp', false, 101),
  (1, 'Theocracy', 'Thần quyền', false, 102),
  (1, 'Communist state', 'Nhà nước cộng sản', false, 103),
  (1, 'Confederation', 'Liên minh các bang (Confederation)', false, 104),
  (2, 'The Declaration of Independence', 'Tuyên ngôn Độc lập', false, 100),
  (2, 'The Bill of Rights', 'Tuyên ngôn Nhân quyền', false, 101),
  (2, 'The Articles of Confederation', 'Các Điều khoản Liên hiệp', false, 102),
  (2, 'Federal statutes passed by Congress', 'Các đạo luật liên bang do Quốc hội thông qua', false, 103),
  (2, 'Executive orders by the President', 'Sắc lệnh của Tổng thống', false, 104),
  (3, 'Sets the price of goods', 'Quy định giá hàng hóa', false, 100),
  (3, 'Names the national anthem', 'Đặt tên quốc ca', false, 101),
  (3, 'Lists the 50 states', 'Liệt kê 50 tiểu bang', false, 102),
  (3, 'Sets the school curriculum', 'Quy định chương trình giảng dạy', false, 103),
  (3, 'Declares the national religion', 'Tuyên bố quốc giáo', false, 104),
  (4, 'Power of the king', 'Quyền lực của vua', false, 100),
  (4, 'Authority of the Supreme Court', 'Quyền lực của Tòa án Tối cao', false, 101),
  (4, 'The right to bear arms', 'Quyền sở hữu vũ khí', false, 102),
  (4, 'Federal sovereignty over the states', 'Chủ quyền liên bang lên các bang', false, 103),
  (4, 'Loyalty to the President', 'Lòng trung thành với Tổng thống', false, 104),
  (5, 'A presidential signature', 'Chữ ký của Tổng thống', false, 100),
  (5, 'A Supreme Court ruling', 'Phán quyết của Tòa án Tối cao', false, 101),
  (5, 'A national referendum', 'Trưng cầu dân ý quốc gia', false, 102),
  (5, 'An executive order', 'Sắc lệnh Hành pháp', false, 103),
  (5, 'A vote in only the Senate', 'Bỏ phiếu chỉ tại Thượng viện', false, 104),
  (6, 'The right to free healthcare', 'Quyền được chăm sóc y tế miễn phí', false, 100),
  (6, 'The right to a college education', 'Quyền được học đại học', false, 101),
  (6, 'The salary of federal workers', 'Lương công chức liên bang', false, 102),
  (6, 'The borders of each state', 'Ranh giới của mỗi tiểu bang', false, 103),
  (6, 'The president''s authority', 'Thẩm quyền của Tổng thống', false, 104),
  (7, 'Ten (10)', 'Mười (10)', false, 100),
  (7, 'Fifty (50)', 'Năm mươi (50)', false, 101),
  (7, 'Twenty-five (25)', 'Hai mươi lăm (25)', false, 102),
  (7, 'Thirty (30)', 'Ba mươi (30)', false, 103),
  (7, 'Seventeen (17)', 'Mười bảy (17)', false, 104),
  (8, 'It established the federal court system', 'Nó thành lập hệ thống tòa án liên bang', false, 100),
  (8, 'It set the rules for elections', 'Nó đặt ra các quy tắc bầu cử', false, 101),
  (8, 'It created the Bill of Rights', 'Nó tạo ra Tuyên ngôn Nhân quyền', false, 102),
  (8, 'It declared war on France', 'Nó tuyên chiến với Pháp', false, 103),
  (8, 'It defined the three branches of government', 'Nó xác định ba nhánh chính quyền', false, 104),
  (9, 'The U.S. Constitution', 'Hiến pháp Hoa Kỳ', false, 100),
  (9, 'The Bill of Rights', 'Tuyên ngôn Nhân quyền', false, 101),
  (9, 'The Emancipation Proclamation', 'Tuyên ngôn Giải phóng Nô lệ', false, 102),
  (9, 'The Articles of Confederation', 'Các Điều khoản Liên hiệp', false, 103),
  (9, 'The Mayflower Compact', 'Hiệp ước Mayflower', false, 104),
  (10, 'Monarchy', 'Quân chủ', false, 100),
  (10, 'Censorship', 'Kiểm duyệt', false, 101),
  (10, 'State religion', 'Quốc giáo', false, 102),
  (10, 'Mandatory military service', 'Nghĩa vụ quân sự bắt buộc', false, 103),
  (10, 'Hereditary leadership', 'Lãnh đạo cha truyền con nối', false, 104),
  (11, 'U.S. Constitution', 'Hiến pháp Hoa Kỳ', false, 100),
  (11, 'Bill of Rights', 'Tuyên ngôn Nhân quyền', false, 101),
  (11, 'Federalist Papers', 'Các Bài báo Liên bang', false, 102),
  (11, 'Articles of Confederation', 'Các Điều khoản Liên hiệp', false, 103),
  (11, 'Gettysburg Address', 'Diễn văn Gettysburg', false, 104),
  (12, 'Socialism', 'Chủ nghĩa xã hội', false, 100),
  (12, 'Communism', 'Chủ nghĩa cộng sản', false, 101),
  (12, 'Command economy', 'Nền kinh tế chỉ huy', false, 102),
  (12, 'Feudalism', 'Chủ nghĩa phong kiến', false, 103),
  (12, 'Barter economy', 'Nền kinh tế trao đổi hàng hóa', false, 104),
  (13, 'Only judges decide what is legal', 'Chỉ thẩm phán mới quyết định điều gì hợp pháp', false, 100),
  (13, 'Police can change laws', 'Cảnh sát có thể thay đổi luật', false, 101),
  (13, 'The president writes the laws', 'Tổng thống viết luật', false, 102),
  (13, 'Wealthy people are exempt from taxes', 'Người giàu được miễn thuế', false, 103),
  (13, 'Only Congress is required to follow the law', 'Chỉ Quốc hội mới phải tuân thủ luật', false, 104),
  (14, 'The Gettysburg Address', 'Diễn văn Gettysburg', false, 100),
  (14, 'The Emancipation Proclamation', 'Tuyên ngôn Giải phóng Nô lệ', false, 101),
  (14, 'The Treaty of Versailles', 'Hiệp ước Versailles', false, 102),
  (14, 'The Monroe Doctrine', 'Học thuyết Monroe', false, 103),
  (14, 'The Marshall Plan', 'Kế hoạch Marshall', false, 104),
  (15, 'To save government money', 'Để tiết kiệm ngân sách chính phủ', false, 100),
  (15, 'To represent each political party', 'Để đại diện cho mỗi đảng phái chính trị', false, 101),
  (15, 'To make laws faster', 'Để làm luật nhanh hơn', false, 102),
  (15, 'To divide the country into regions', 'Để chia đất nước thành các vùng', false, 103),
  (15, 'To match the three founding documents', 'Để khớp với ba văn kiện lập quốc', false, 104),
  (16, 'Federal, state, and local', 'Liên bang, tiểu bang và địa phương', false, 100),
  (16, 'Military, civilian, and judicial', 'Quân sự, dân sự và tư pháp', false, 101),
  (16, 'House, Senate, and Cabinet', 'Hạ viện, Thượng viện và Nội các', false, 102),
  (16, 'President, Vice President, and Speaker', 'Tổng thống, Phó Tổng thống và Chủ tịch Hạ viện', false, 103),
  (16, 'Public, private, and civic', 'Công, tư và công dân', false, 104),
  (17, 'Legislative branch', 'Nhánh Lập pháp', false, 100),
  (17, 'Judicial branch', 'Nhánh Tư pháp', false, 101),
  (17, 'Military branch', 'Nhánh Quân sự', false, 102),
  (17, 'Diplomatic branch', 'Nhánh Ngoại giao', false, 103),
  (17, 'State branch', 'Nhánh Tiểu bang', false, 104),
  (18, 'The President', 'Tổng thống', false, 100),
  (18, 'The Supreme Court', 'Tòa án Tối cao', false, 101),
  (18, 'The Cabinet', 'Nội các', false, 102),
  (18, 'The Department of Justice', 'Bộ Tư pháp', false, 103),
  (18, 'State governors', 'Các thống đốc tiểu bang', false, 104),
  (19, 'House and Cabinet', 'Hạ viện và Nội các', false, 100),
  (19, 'Senate and Supreme Court', 'Thượng viện và Tòa án Tối cao', false, 101),
  (19, 'House and Electoral College', 'Hạ viện và Cử tri đoàn', false, 102),
  (19, 'Upper Chamber and Lower Chamber', 'Thượng viện và Hạ viện (cách gọi sai)', false, 103),
  (19, 'House of Lords and House of Commons', 'Viện Quý tộc và Viện Bình dân', false, 104),
  (20, 'Signs treaties into law', 'Ký các hiệp ước thành luật', false, 100),
  (20, 'Commands the military', 'Chỉ huy quân đội', false, 101),
  (20, 'Vetoes bills', 'Phủ quyết dự luật', false, 102),
  (20, 'Interprets the Constitution', 'Giải thích Hiến pháp', false, 103),
  (20, 'Appoints federal judges', 'Bổ nhiệm thẩm phán liên bang', false, 104),
  (21, 'Fifty (50)', 'Năm mươi (50)', false, 100),
  (21, 'Two hundred (200)', 'Hai trăm (200)', false, 101),
  (21, 'Four hundred thirty-five (435)', 'Bốn trăm ba mươi lăm (435)', false, 102),
  (21, 'Twenty-five (25)', 'Hai mươi lăm (25)', false, 103),
  (21, 'Five hundred thirty-five (535)', 'Năm trăm ba mươi lăm (535)', false, 104),
  (22, 'Two (2) years', 'Hai (2) năm', false, 100),
  (22, 'Four (4) years', 'Bốn (4) năm', false, 101),
  (22, 'Eight (8) years', 'Tám (8) năm', false, 102),
  (22, 'Lifetime', 'Trọn đời', false, 103),
  (22, 'Ten (10) years', 'Mười (10) năm', false, 104),
  (23, 'Bernie Sanders', 'Bernie Sanders', false, 100),
  (23, 'Elizabeth Warren', 'Elizabeth Warren', false, 101),
  (23, 'Marco Rubio', 'Marco Rubio', false, 102),
  (23, 'Lindsey Graham', 'Lindsey Graham', false, 103),
  (23, 'Chuck Schumer', 'Chuck Schumer', false, 104),
  (24, 'One hundred (100)', 'Một trăm (100)', false, 100),
  (24, 'Two hundred fifty (250)', 'Hai trăm năm mươi (250)', false, 101),
  (24, 'Five hundred thirty-eight (538)', 'Năm trăm ba mươi tám (538)', false, 102),
  (24, 'Three hundred (300)', 'Ba trăm (300)', false, 103),
  (24, 'Five hundred (500)', 'Năm trăm (500)', false, 104),
  (25, 'Six (6) years', 'Sáu (6) năm', false, 100),
  (25, 'Four (4) years', 'Bốn (4) năm', false, 101),
  (25, 'Eight (8) years', 'Tám (8) năm', false, 102),
  (25, 'One (1) year', 'Một (1) năm', false, 103),
  (25, 'Lifetime', 'Trọn đời', false, 104),
  (26, 'To save government money', 'Để tiết kiệm ngân sách', false, 100),
  (26, 'Because they have less power', 'Vì họ có ít quyền lực hơn', false, 101),
  (26, 'Because they are younger', 'Vì họ trẻ hơn', false, 102),
  (26, 'To match the Constitution''s original draft', 'Để khớp với bản dự thảo gốc của Hiến pháp', false, 103),
  (26, 'Because their districts are smaller', 'Vì khu vực bầu cử của họ nhỏ hơn', false, 104),
  (27, 'One (1)', 'Một (1)', false, 100),
  (27, 'Three (3)', 'Ba (3)', false, 101),
  (27, 'Four (4)', 'Bốn (4)', false, 102),
  (27, 'Based on population', 'Tùy theo dân số', false, 103),
  (27, 'Five (5)', 'Năm (5)', false, 104),
  (28, 'To match population size', 'Để khớp với quy mô dân số', false, 100),
  (28, 'For party balance', 'Để cân bằng đảng phái', false, 101),
  (28, 'To represent each gender', 'Để đại diện cho mỗi giới tính', false, 102),
  (28, 'Because there are two political parties', 'Vì có hai đảng chính trị', false, 103),
  (28, 'To divide work in half', 'Để chia đôi công việc', false, 104),
  (29, 'Margaret Thornhill', 'Margaret Thornhill', false, 100),
  (29, 'Bernard Whitfield', 'Bernard Whitfield', false, 101),
  (29, 'Eleanor Castellanos', 'Eleanor Castellanos', false, 102),
  (29, 'Harrison Blackwood', 'Harrison Blackwood', false, 103),
  (29, 'Patricia Renteria', 'Patricia Renteria', false, 104),
  (30, 'Kevin McCarthy', 'Kevin McCarthy', false, 100),
  (30, 'Nancy Pelosi', 'Nancy Pelosi', false, 101),
  (30, 'Paul Ryan', 'Paul Ryan', false, 102),
  (30, 'John Boehner', 'John Boehner', false, 103),
  (30, 'Hakeem Jeffries', 'Hakeem Jeffries', false, 104),
  (31, 'Citizens of the entire country', 'Công dân của cả nước', false, 100),
  (31, 'Citizens of their congressional district', 'Công dân trong khu vực bầu cử của họ', false, 101),
  (31, 'The president', 'Tổng thống', false, 102),
  (31, 'Their political party', 'Đảng phái của họ', false, 103),
  (31, 'Federal employees', 'Nhân viên liên bang', false, 104),
  (32, 'The state legislature', 'Cơ quan lập pháp tiểu bang', false, 100),
  (32, 'The President', 'Tổng thống', false, 101),
  (32, 'The Electoral College', 'Cử tri đoàn', false, 102),
  (32, 'Citizens of the entire country', 'Công dân của cả nước', false, 103),
  (32, 'The state governor', 'Thống đốc tiểu bang', false, 104),
  (33, 'Citizens of the entire state', 'Công dân của cả tiểu bang', false, 100),
  (33, 'Citizens of the entire country', 'Công dân của cả nước', false, 101),
  (33, 'Their political party', 'Đảng phái của họ', false, 102),
  (33, 'The state governor', 'Thống đốc tiểu bang', false, 103),
  (33, 'Federal employees in their region', 'Nhân viên liên bang trong vùng', false, 104),
  (34, 'Citizens of the entire state', 'Công dân của cả tiểu bang', false, 100),
  (34, 'The state legislature', 'Cơ quan lập pháp tiểu bang', false, 101),
  (34, 'The President', 'Tổng thống', false, 102),
  (34, 'The Electoral College', 'Cử tri đoàn', false, 103),
  (34, 'The Senate', 'Thượng viện', false, 104),
  (35, 'Because of the state''s land size', 'Vì diện tích đất của tiểu bang', false, 100),
  (35, 'Because of the state''s wealth', 'Vì sự giàu có của tiểu bang', false, 101),
  (35, 'Because they joined the Union earlier', 'Vì họ gia nhập Liên bang sớm hơn', false, 102),
  (35, 'Because of the number of cities', 'Vì số lượng thành phố', false, 103),
  (35, 'Based on the governor''s request', 'Theo yêu cầu của thống đốc', false, 104),
  (36, 'Two (2) years', 'Hai (2) năm', false, 100),
  (36, 'Six (6) years', 'Sáu (6) năm', false, 101),
  (36, 'Eight (8) years', 'Tám (8) năm', false, 102),
  (36, 'Lifetime', 'Trọn đời', false, 103),
  (36, 'Ten (10) years', 'Mười (10) năm', false, 104),
  (37, 'Because of the 1st Amendment', 'Vì Tu chính án thứ 1', false, 100),
  (37, 'Because of the Bill of Rights', 'Vì Tuyên ngôn Nhân quyền', false, 101),
  (37, 'Because of the 14th Amendment', 'Vì Tu chính án thứ 14', false, 102),
  (37, 'Because of the Electoral College', 'Vì Cử tri đoàn', false, 103),
  (37, 'To follow British tradition', 'Để theo truyền thống Anh', false, 104),
  (38, 'Donald Trump', 'Donald Trump', false, 100),
  (38, 'Barack Obama', 'Barack Obama', false, 101),
  (38, 'Bill Clinton', 'Bill Clinton', false, 102),
  (38, 'George W. Bush', 'George W. Bush', false, 103),
  (38, 'Jimmy Carter', 'Jimmy Carter', false, 104),
  (39, 'Mike Pence', 'Mike Pence', false, 100),
  (39, 'Joe Biden', 'Joe Biden', false, 101),
  (39, 'Al Gore', 'Al Gore', false, 102),
  (39, 'Dick Cheney', 'Dick Cheney', false, 103),
  (39, 'JD Vance', 'JD Vance', false, 104),
  (40, 'The Speaker of the House', 'Chủ tịch Hạ viện', false, 100),
  (40, 'The Secretary of State', 'Ngoại trưởng', false, 101),
  (40, 'The Chief Justice', 'Chánh án', false, 102),
  (40, 'The President pro tempore of the Senate', 'Chủ tịch lâm thời Thượng viện', false, 103),
  (40, 'The Senate Majority Leader', 'Lãnh đạo Đa số Thượng viện', false, 104),
  (41, 'Writes laws', 'Viết luật', false, 100),
  (41, 'Declares war', 'Tuyên chiến', false, 101),
  (41, 'Sets the federal budget', 'Lập ngân sách liên bang', false, 102),
  (41, 'Removes Supreme Court justices', 'Bãi nhiệm thẩm phán Tòa án Tối cao', false, 103),
  (41, 'Selects state governors', 'Chọn thống đốc tiểu bang', false, 104),
  (42, 'The Secretary of Defense', 'Bộ trưởng Quốc phòng', false, 100),
  (42, 'A four-star general', 'Một tướng bốn sao', false, 101),
  (42, 'The Vice President', 'Phó Tổng thống', false, 102),
  (42, 'The Speaker of the House', 'Chủ tịch Hạ viện', false, 103),
  (42, 'The Joint Chiefs of Staff', 'Hội đồng Tham mưu trưởng Liên quân', false, 104),
  (43, 'The Speaker of the House', 'Chủ tịch Hạ viện', false, 100),
  (43, 'The Vice President', 'Phó Tổng thống', false, 101),
  (43, 'The Chief Justice', 'Chánh án', false, 102),
  (43, 'The Senate Majority Leader', 'Lãnh đạo Đa số Thượng viện', false, 103),
  (43, 'The Attorney General', 'Bộ trưởng Tư pháp', false, 104),
  (44, 'The Speaker of the House', 'Chủ tịch Hạ viện', false, 100),
  (44, 'The Supreme Court', 'Tòa án Tối cao', false, 101),
  (44, 'The Vice President', 'Phó Tổng thống', false, 102),
  (44, 'The Senate', 'Thượng viện', false, 103),
  (44, 'State governors', 'Các thống đốc tiểu bang', false, 104),
  (45, 'The Senate', 'Thượng viện', false, 100),
  (45, 'The Chief Justice', 'Chánh án', false, 101),
  (45, 'The Speaker of the House', 'Chủ tịch Hạ viện', false, 102),
  (45, 'The Attorney General', 'Bộ trưởng Tư pháp', false, 103),
  (45, 'State governors', 'Các thống đốc tiểu bang', false, 104),
  (46, 'Senate', 'Thượng viện', false, 100),
  (46, 'Supreme Court', 'Tòa án Tối cao', false, 101),
  (46, 'House of Representatives', 'Hạ viện', false, 102),
  (46, 'State legislatures', 'Các cơ quan lập pháp tiểu bang', false, 103),
  (46, 'County boards', 'Hội đồng quận', false, 104),
  (47, 'Writes laws', 'Viết luật', false, 100),
  (47, 'Decides court cases', 'Xét xử các vụ án', false, 101),
  (47, 'Approves treaties', 'Phê chuẩn hiệp ước', false, 102),
  (47, 'Elects the President', 'Bầu Tổng thống', false, 103),
  (47, 'Commands the military', 'Chỉ huy quân đội', false, 104),
  (48, 'Speaker of the House', 'Chủ tịch Hạ viện', false, 100),
  (48, 'Senate Majority Leader', 'Lãnh đạo Đa số Thượng viện', false, 101),
  (48, 'Chief Justice', 'Chánh án', false, 102),
  (48, 'Director of the FBI', 'Giám đốc FBI', false, 103),
  (48, 'Chairman of the Federal Reserve', 'Chủ tịch Cục Dự trữ Liên bang', false, 104),
  (49, 'It writes the federal budget', 'Nó lập ngân sách liên bang', false, 100),
  (49, 'It selects Supreme Court justices', 'Nó chọn thẩm phán Tòa án Tối cao', false, 101),
  (49, 'It approves treaties', 'Nó phê chuẩn các hiệp ước', false, 102),
  (49, 'It impeaches the president', 'Nó luận tội tổng thống', false, 103),
  (49, 'It enforces voting laws', 'Nó thực thi luật bầu cử', false, 104),
  (50, 'Senate', 'Thượng viện', false, 100),
  (50, 'Cabinet', 'Nội các', false, 101),
  (50, 'House of Representatives', 'Hạ viện', false, 102),
  (50, 'State legislatures', 'Các cơ quan lập pháp tiểu bang', false, 103),
  (50, 'The Department of Justice', 'Bộ Tư pháp', false, 104),
  (51, 'Writes laws', 'Viết luật', false, 100),
  (51, 'Enforces laws', 'Thực thi luật', false, 101),
  (51, 'Sets the federal budget', 'Lập ngân sách liên bang', false, 102),
  (51, 'Commands the military', 'Chỉ huy quân đội', false, 103),
  (51, 'Negotiates treaties', 'Đàm phán hiệp ước', false, 104),
  (52, 'Federal District Court', 'Tòa án Quận Liên bang', false, 100),
  (52, 'Court of Appeals', 'Tòa Phúc thẩm', false, 101),
  (52, 'State Supreme Court', 'Tòa án Tối cao Tiểu bang', false, 102),
  (52, 'International Court of Justice', 'Tòa án Công lý Quốc tế', false, 103),
  (52, 'Tax Court', 'Tòa án Thuế', false, 104),
  (53, 'Seven (7)', 'Bảy (7)', false, 100),
  (53, 'Eleven (11)', 'Mười một (11)', false, 101),
  (53, 'Five (5)', 'Năm (5)', false, 102),
  (53, 'Thirteen (13)', 'Mười ba (13)', false, 103),
  (53, 'Twelve (12)', 'Mười hai (12)', false, 104),
  (54, 'Three (3)', 'Ba (3)', false, 100),
  (54, 'Seven (7)', 'Bảy (7)', false, 101),
  (54, 'Nine (9)', 'Chín (9)', false, 102),
  (54, 'A simple majority of those present', 'Đa số đơn giản của những người có mặt', false, 103),
  (54, 'Four (4)', 'Bốn (4)', false, 104),
  (55, 'Four (4) years', 'Bốn (4) năm', false, 100),
  (55, 'Six (6) years', 'Sáu (6) năm', false, 101),
  (55, 'Ten (10) years', 'Mười (10) năm', false, 102),
  (55, 'Until the next election', 'Cho đến cuộc bầu cử kế tiếp', false, 103),
  (55, 'Twenty (20) years', 'Hai mươi (20) năm', false, 104),
  (56, 'To save money on elections', 'Để tiết kiệm chi phí bầu cử', false, 100),
  (56, 'To keep them loyal to the President', 'Để họ trung thành với Tổng thống', false, 101),
  (56, 'Because they are elected', 'Vì họ được bầu cử', false, 102),
  (56, 'To match British tradition', 'Để theo truyền thống Anh', false, 103),
  (56, 'So they can be fired easily', 'Để có thể dễ dàng sa thải họ', false, 104),
  (57, 'Sonia Sotomayor', 'Sonia Sotomayor', false, 100),
  (57, 'Clarence Thomas', 'Clarence Thomas', false, 101),
  (57, 'Samuel Alito', 'Samuel Alito', false, 102),
  (57, 'Ruth Bader Ginsburg', 'Ruth Bader Ginsburg', false, 103),
  (57, 'Brett Kavanaugh', 'Brett Kavanaugh', false, 104),
  (58, 'Issue driver''s licenses', 'Cấp giấy phép lái xe', false, 100),
  (58, 'Run public schools', 'Điều hành trường công', false, 101),
  (58, 'Approve marriages', 'Phê duyệt hôn nhân', false, 102),
  (58, 'Set state speed limits', 'Đặt giới hạn tốc độ tiểu bang', false, 103),
  (58, 'Hire local police', 'Tuyển cảnh sát địa phương', false, 104),
  (59, 'Print paper money', 'In tiền giấy', false, 100),
  (59, 'Declare war', 'Tuyên chiến', false, 101),
  (59, 'Make treaties', 'Ký hiệp ước', false, 102),
  (59, 'Issue passports', 'Cấp hộ chiếu', false, 103),
  (59, 'Mint coins', 'Đúc tiền xu', false, 104),
  (60, 'It abolished slavery', 'Nó bãi bỏ chế độ nô lệ', false, 100),
  (60, 'It established freedom of speech', 'Nó thiết lập tự do ngôn luận', false, 101),
  (60, 'It gave women the right to vote', 'Nó trao cho phụ nữ quyền bầu cử', false, 102),
  (60, 'It set the term limits for the President', 'Nó giới hạn nhiệm kỳ Tổng thống', false, 103),
  (60, 'It created the Supreme Court', 'Nó thành lập Tòa án Tối cao', false, 104),
  (61, 'Gavin Newsom', 'Gavin Newsom', false, 100),
  (61, 'Ron DeSantis', 'Ron DeSantis', false, 101),
  (61, 'Brian Kemp', 'Brian Kemp', false, 102),
  (61, 'Kathy Hochul', 'Kathy Hochul', false, 103),
  (61, 'Josh Shapiro', 'Josh Shapiro', false, 104),
  (62, 'Houston', 'Houston', false, 100),
  (62, 'Dallas', 'Dallas', false, 101),
  (62, 'San Antonio', 'San Antonio', false, 102),
  (62, 'El Paso', 'El Paso', false, 103),
  (62, 'Fort Worth', 'Fort Worth', false, 104),
  (63, 'Citizens 16 and older can vote', 'Công dân từ 16 tuổi trở lên có thể bỏ phiếu', false, 100),
  (63, 'Only landowners can vote', 'Chỉ chủ đất mới có thể bỏ phiếu', false, 101),
  (63, 'Only military veterans can vote', 'Chỉ cựu chiến binh mới có thể bỏ phiếu', false, 102),
  (63, 'Voting is mandatory for all citizens', 'Bỏ phiếu là bắt buộc với mọi công dân', false, 103),
  (63, 'You must pass a literacy test to vote', 'Bạn phải qua kỳ thi đọc viết để bỏ phiếu', false, 104),
  (64, 'Lawful permanent residents', 'Thường trú nhân hợp pháp', false, 100),
  (64, 'Anyone over 18', 'Bất kỳ ai trên 18 tuổi', false, 101),
  (64, 'Visa holders', 'Người có visa', false, 102),
  (64, 'Refugees with work permits', 'Người tị nạn có giấy phép lao động', false, 103),
  (64, 'Anyone with a Social Security number', 'Bất kỳ ai có số An sinh Xã hội', false, 104),
  (65, 'Freedom of speech, the right to free housing, and freedom of religion', 'Tự do ngôn luận, quyền có nhà ở miễn phí, và tự do tôn giáo', false, 100),
  (65, 'The right to a paid job, freedom of assembly, and freedom of speech', 'Quyền có việc làm được trả lương, tự do hội họp, và tự do ngôn luận', false, 101),
  (65, 'Freedom of religion, the right to free education, and the right to bear arms', 'Tự do tôn giáo, quyền được giáo dục miễn phí, và quyền mang vũ khí', false, 102),
  (65, 'Freedom of speech, the right to a free phone, and freedom of assembly', 'Tự do ngôn luận, quyền có điện thoại miễn phí, và tự do hội họp', false, 103),
  (65, 'The right to free internet, freedom of religion, and freedom of speech', 'Quyền sử dụng internet miễn phí, tự do tôn giáo, và tự do ngôn luận', false, 104),
  (66, 'The President', 'Tổng thống', false, 100),
  (66, 'The U.S. military', 'Quân đội Hoa Kỳ', false, 101),
  (66, 'Congress', 'Quốc hội', false, 102),
  (66, 'The Founding Fathers', 'Các Nhà lập quốc', false, 103),
  (66, 'Each individual state', 'Mỗi tiểu bang riêng biệt', false, 104),
  (67, 'Pay extra taxes', 'Trả thêm thuế', false, 100),
  (67, 'Vote in every election', 'Bỏ phiếu trong mọi cuộc bầu cử', false, 101),
  (67, 'Speak only English at home', 'Chỉ nói tiếng Anh ở nhà', false, 102),
  (67, 'Donate to charity each year', 'Quyên góp từ thiện hàng năm', false, 103),
  (67, 'Attend church on Sundays', 'Đi nhà thờ vào Chủ nhật', false, 104),
  (68, 'Marry a U.S. citizen automatically', 'Tự động trở thành công dân khi kết hôn', false, 100),
  (68, 'Buy U.S. real estate', 'Mua bất động sản Mỹ', false, 101),
  (68, 'Live in the U.S. for 1 year', 'Sống tại Mỹ trong 1 năm', false, 102),
  (68, 'Get a U.S. job', 'Có việc làm tại Mỹ', false, 103),
  (68, 'Pay $10,000 to the government', 'Trả 10.000 đô la cho chính phủ', false, 104),
  (69, 'Pay private membership fees', 'Đóng phí thành viên tư nhân', false, 100),
  (69, 'Buy bonds from foreign countries', 'Mua trái phiếu nước ngoài', false, 101),
  (69, 'Boycott U.S. products', 'Tẩy chay sản phẩm Mỹ', false, 102),
  (69, 'Renounce other citizenships', 'Từ bỏ các quốc tịch khác', false, 103),
  (69, 'Move to another country', 'Chuyển sang nước khác', false, 104),
  (70, 'Buy American products only', 'Chỉ mua hàng Mỹ', false, 100),
  (70, 'Donate to the President''s campaign', 'Quyên góp cho chiến dịch của Tổng thống', false, 101),
  (70, 'Speak English fluently', 'Nói tiếng Anh trôi chảy', false, 102),
  (70, 'Attend U.S. cultural events', 'Tham dự các sự kiện văn hóa Mỹ', false, 103),
  (70, 'Live in Washington, D.C.', 'Sống ở Washington, D.C.', false, 104),
  (71, 'To pay the President''s salary only', 'Chỉ để trả lương cho Tổng thống', false, 100),
  (71, 'To support foreign governments', 'Để hỗ trợ chính phủ nước ngoài', false, 101),
  (71, 'Because banks require it', 'Vì các ngân hàng yêu cầu', false, 102),
  (71, 'To register for elections', 'Để đăng ký bầu cử', false, 103),
  (71, 'To get a passport', 'Để có hộ chiếu', false, 104),
  (72, 'To get a discount on college tuition', 'Để được giảm học phí đại học', false, 100),
  (72, 'To receive a Social Security number', 'Để nhận số An sinh Xã hội', false, 101),
  (72, 'To enter the military immediately', 'Để nhập ngũ ngay lập tức', false, 102),
  (72, 'To get a driver''s license', 'Để có giấy phép lái xe', false, 103),
  (72, 'To vote in federal elections', 'Để bỏ phiếu trong bầu cử liên bang', false, 104),
  (73, 'Free land grants from the king', 'Cấp đất miễn phí từ nhà vua', false, 100),
  (73, 'To spread Catholicism', 'Để truyền bá Công giáo', false, 101),
  (73, 'To find precious metals only', 'Để chỉ tìm kim loại quý', false, 102),
  (73, 'To establish a monarchy', 'Để thiết lập chế độ quân chủ', false, 103),
  (73, 'To trade weapons', 'Để buôn bán vũ khí', false, 104),
  (74, 'Vikings', 'Người Viking', false, 100),
  (74, 'Spanish conquistadors', 'Conquistador Tây Ban Nha', false, 101),
  (74, 'African settlers', 'Người định cư châu Phi', false, 102),
  (74, 'Chinese explorers', 'Nhà thám hiểm Trung Quốc', false, 103),
  (74, 'Polynesian voyagers', 'Người Polynesia', false, 104),
  (75, 'Native Americans', 'Người bản địa Mỹ', false, 100),
  (75, 'Irish immigrants', 'Người nhập cư Ireland', false, 101),
  (75, 'European indentured servants', 'Người hầu Châu Âu', false, 102),
  (75, 'Chinese laborers', 'Người lao động Trung Quốc', false, 103),
  (75, 'Indigenous Caribbean peoples', 'Người bản địa vùng Caribe', false, 104),
  (76, 'Civil War', 'Nội chiến', false, 100),
  (76, 'French and Indian War', 'Chiến tranh Pháp và Da Đỏ', false, 101),
  (76, 'War of 1812', 'Chiến tranh năm 1812', false, 102),
  (76, 'Mexican-American War', 'Chiến tranh Mexico-Mỹ', false, 103),
  (76, 'Spanish-American War', 'Chiến tranh Tây Ban Nha-Mỹ', false, 104),
  (77, 'Religious persecution by the British king', 'Vua Anh đàn áp tôn giáo', false, 100),
  (77, 'To free the slaves', 'Để giải phóng nô lệ', false, 101),
  (77, 'To establish a national bank', 'Để thành lập ngân hàng quốc gia', false, 102),
  (77, 'Disagreement over the gold standard', 'Bất đồng về bản vị vàng', false, 103),
  (77, 'Refusal to fight in European wars', 'Từ chối tham gia các cuộc chiến châu Âu', false, 104),
  (78, 'George Washington', 'George Washington', false, 100),
  (78, 'Benjamin Franklin', 'Benjamin Franklin', false, 101),
  (78, 'John Adams', 'John Adams', false, 102),
  (78, 'James Madison', 'James Madison', false, 103),
  (78, 'Alexander Hamilton', 'Alexander Hamilton', false, 104),
  (79, 'July 4, 1789', 'Ngày 4 tháng 7 năm 1789', false, 100),
  (79, 'September 17, 1787', 'Ngày 17 tháng 9 năm 1787', false, 101),
  (79, 'March 4, 1789', 'Ngày 4 tháng 3 năm 1789', false, 102),
  (79, 'November 11, 1776', 'Ngày 11 tháng 11 năm 1776', false, 103),
  (79, 'December 25, 1776', 'Ngày 25 tháng 12 năm 1776', false, 104),
  (80, 'Battle of Gettysburg', 'Trận Gettysburg', false, 100),
  (80, 'Battle of Antietam', 'Trận Antietam', false, 101),
  (80, 'Pearl Harbor', 'Trân Châu Cảng', false, 102),
  (80, 'D-Day', 'Ngày D (đổ bộ Normandy)', false, 103),
  (80, 'Battle of the Alamo', 'Trận Alamo', false, 104),
  (81, 'Massachusetts, Vermont, Connecticut, Maryland, Rhode Island', 'Massachusetts, Vermont, Connecticut, Maryland, Rhode Island', false, 100),
  (81, 'Pennsylvania, Delaware, Kentucky, Georgia, New Hampshire', 'Pennsylvania, Delaware, Kentucky, Georgia, New Hampshire', false, 101),
  (81, 'Virginia, Maryland, Tennessee, Connecticut, Delaware', 'Virginia, Maryland, Tennessee, Connecticut, Delaware', false, 102),
  (81, 'New York, Ohio, Massachusetts, Georgia, Pennsylvania', 'New York, Ohio, Massachusetts, Georgia, Pennsylvania', false, 103),
  (81, 'New Jersey, Maine, South Carolina, Rhode Island, Virginia', 'New Jersey, Maine, South Carolina, Rhode Island, Virginia', false, 104),
  (82, 'Declaration of Independence', 'Tuyên ngôn Độc lập', false, 100),
  (82, 'Bill of Rights', 'Tuyên ngôn Nhân quyền', false, 101),
  (82, 'Articles of Confederation', 'Các Điều khoản Liên minh', false, 102),
  (82, 'Mayflower Compact', 'Hiệp ước Mayflower', false, 103),
  (82, 'Emancipation Proclamation', 'Tuyên ngôn Giải phóng Nô lệ', false, 104),
  (83, 'Thomas Jefferson', 'Thomas Jefferson', false, 100),
  (83, 'George Washington', 'George Washington', false, 101),
  (83, 'Benjamin Franklin', 'Benjamin Franklin', false, 102),
  (83, 'John Adams', 'John Adams', false, 103),
  (83, 'Patrick Henry', 'Patrick Henry', false, 104),
  (84, 'They declared independence from Britain', 'Chúng tuyên bố độc lập khỏi Anh', false, 100),
  (84, 'They ended slavery', 'Chúng chấm dứt chế độ nô lệ', false, 101),
  (84, 'They established the Bill of Rights', 'Chúng thiết lập Tuyên ngôn Nhân quyền', false, 102),
  (84, 'They created the two-party system', 'Chúng tạo ra hệ thống hai đảng', false, 103),
  (84, 'They negotiated peace with Britain', 'Chúng đàm phán hòa bình với Anh', false, 104),
  (85, 'First president of the United States', 'Tổng thống đầu tiên của Hoa Kỳ', false, 100),
  (85, 'Wrote the U.S. Constitution', 'Viết Hiến pháp Hoa Kỳ', false, 101),
  (85, 'Led the Continental Army', 'Chỉ huy Quân đội Lục địa', false, 102),
  (85, 'Chief Justice of the Supreme Court', 'Chánh án Tòa án Tối cao', false, 103),
  (85, 'Founded Harvard University', 'Thành lập Đại học Harvard', false, 104),
  (86, 'Wrote the Declaration of Independence', 'Viết Tuyên ngôn Độc lập', false, 100),
  (86, 'First Secretary of the Treasury', 'Bộ trưởng Ngân khố đầu tiên', false, 101),
  (86, 'Founded the University of Virginia', 'Thành lập Đại học Virginia', false, 102),
  (86, 'Discovered electricity', 'Khám phá ra điện', false, 103),
  (86, 'Negotiated the Louisiana Purchase', 'Đàm phán việc mua Louisiana', false, 104),
  (87, 'First president of the United States', 'Tổng thống đầu tiên của Hoa Kỳ', false, 100),
  (87, '"Father of the Constitution"', '"Cha đẻ của Hiến pháp"', false, 101),
  (87, 'First Secretary of the Treasury', 'Bộ trưởng Ngân khố đầu tiên', false, 102),
  (87, 'Led the Union during the Civil War', 'Lãnh đạo Liên bang trong Nội chiến', false, 103),
  (87, 'First Postmaster General', 'Tổng Giám đốc Bưu điện đầu tiên', false, 104),
  (88, 'Wrote the Declaration of Independence', 'Viết Tuyên ngôn Độc lập', false, 100),
  (88, 'First president of the United States', 'Tổng thống đầu tiên của Hoa Kỳ', false, 101),
  (88, 'Made the Louisiana Purchase', 'Thực hiện vụ mua Louisiana', false, 102),
  (88, 'First Secretary of the Treasury', 'Bộ trưởng Ngân khố đầu tiên', false, 103),
  (88, 'Freed the slaves', 'Giải phóng nô lệ', false, 104),
  (89, 'First president of the United States', 'Tổng thống đầu tiên của Hoa Kỳ', false, 100),
  (89, 'Wrote the Declaration of Independence', 'Viết Tuyên ngôn Độc lập', false, 101),
  (89, '"Father of the Constitution"', '"Cha đẻ của Hiến pháp"', false, 102),
  (89, 'Chief Justice of the Supreme Court', 'Chánh án Tòa án Tối cao', false, 103),
  (89, 'Discovered electricity', 'Khám phá ra điện', false, 104),
  (90, 'Florida', 'Florida', false, 100),
  (90, 'Alaska', 'Alaska', false, 101),
  (90, 'Texas', 'Texas', false, 102),
  (90, 'California', 'California', false, 103),
  (90, 'Oregon Territory', 'Lãnh thổ Oregon', false, 104),
  (91, 'World War I', 'Thế chiến thứ nhất', false, 100),
  (91, 'World War II', 'Thế chiến thứ hai', false, 101),
  (91, 'Korean War', 'Chiến tranh Triều Tiên', false, 102),
  (91, 'Vietnam War', 'Chiến tranh Việt Nam', false, 103),
  (91, 'American Revolution', 'Cách mạng Mỹ', false, 104),
  (92, 'The Revolutionary War', 'Chiến tranh Cách mạng', false, 100),
  (92, 'The War of 1812', 'Chiến tranh năm 1812', false, 101),
  (92, 'The Mexican-American War', 'Chiến tranh Mexico-Mỹ', false, 102),
  (92, 'The French and Indian War', 'Chiến tranh Pháp và Da Đỏ', false, 103),
  (92, 'The Spanish-American War', 'Chiến tranh Tây Ban Nha-Mỹ', false, 104),
  (93, 'Battle of Bunker Hill', 'Trận Bunker Hill', false, 100),
  (93, 'Battle of Lexington and Concord', 'Trận Lexington và Concord', false, 101),
  (93, 'Battle of Yorktown', 'Trận Yorktown', false, 102),
  (93, 'Boston Tea Party', 'Tiệc trà Boston', false, 103),
  (93, 'Pearl Harbor', 'Trân Châu Cảng', false, 104),
  (94, 'Wrote the Declaration of Independence', 'Viết Tuyên ngôn Độc lập', false, 100),
  (94, 'First president of the United States', 'Tổng thống đầu tiên của Hoa Kỳ', false, 101),
  (94, 'Doubled the size of the country', 'Tăng gấp đôi diện tích đất nước', false, 102),
  (94, 'Led the Allies in World War II', 'Lãnh đạo Đồng minh trong Thế chiến thứ hai', false, 103),
  (94, 'Founded the Federal Reserve', 'Thành lập Cục Dự trữ Liên bang', false, 104),
  (95, 'Ended the Civil War', 'Kết thúc Nội chiến', false, 100),
  (95, 'Gave women the right to vote', 'Cho phụ nữ quyền bỏ phiếu', false, 101),
  (95, 'Created the United States', 'Tạo ra Hoa Kỳ', false, 102),
  (95, 'Allowed African Americans to serve in Congress', 'Cho phép người Mỹ gốc Phi phục vụ trong Quốc hội', false, 103),
  (95, 'Outlawed segregation in schools', 'Cấm phân biệt chủng tộc trong trường học', false, 104),
  (96, 'The Revolutionary War', 'Chiến tranh Cách mạng', false, 100),
  (96, 'The War of 1812', 'Chiến tranh năm 1812', false, 101),
  (96, 'World War I', 'Thế chiến thứ nhất', false, 102),
  (96, 'World War II', 'Thế chiến thứ hai', false, 103),
  (96, 'The Mexican-American War', 'Chiến tranh Mexico-Mỹ', false, 104),
  (97, '13th Amendment', 'Tu chính án thứ 13', false, 100),
  (97, '15th Amendment', 'Tu chính án thứ 15', false, 101),
  (97, '19th Amendment', 'Tu chính án thứ 19', false, 102),
  (97, '1st Amendment', 'Tu chính án thứ 1', false, 103),
  (97, '10th Amendment', 'Tu chính án thứ 10', false, 104),
  (98, 'After the Revolutionary War', 'Sau Chiến tranh Cách mạng', false, 100),
  (98, 'After World War I', 'Sau Thế chiến thứ nhất', false, 101),
  (98, 'When the Constitution was ratified', 'Khi Hiến pháp được phê chuẩn', false, 102),
  (98, 'With the 13th Amendment', 'Với Tu chính án thứ 13', false, 103),
  (98, 'With the 19th Amendment', 'Với Tu chính án thứ 19', false, 104),
  (99, 'Eleanor Roosevelt', 'Eleanor Roosevelt', false, 100),
  (99, 'Rosa Parks', 'Rosa Parks', false, 101),
  (99, 'Abigail Adams', 'Abigail Adams', false, 102),
  (99, 'Dolley Madison', 'Dolley Madison', false, 103),
  (99, 'Clara Barton', 'Clara Barton', false, 104),
  (100, 'Civil War', 'Nội chiến', false, 100),
  (100, 'Spanish-American War', 'Chiến tranh Tây Ban Nha-Mỹ', false, 101),
  (100, 'Mexican-American War', 'Chiến tranh Mexico-Mỹ', false, 102),
  (100, 'War of 1812', 'Chiến tranh năm 1812', false, 103),
  (100, 'American Revolution', 'Cách mạng Mỹ', false, 104),
  (101, 'Because Japan attacked Pearl Harbor', 'Vì Nhật tấn công Trân Châu Cảng', false, 100),
  (101, 'To stop the spread of communism', 'Để ngăn chặn sự lây lan của chủ nghĩa cộng sản', false, 101),
  (101, 'To free Cuba from Spain', 'Để giải phóng Cuba khỏi Tây Ban Nha', false, 102),
  (101, 'To force Iraq out of Kuwait', 'Để buộc Iraq rời khỏi Kuwait', false, 103),
  (101, 'Because Mexico attacked Texas', 'Vì Mexico tấn công Texas', false, 104),
  (102, 'Theodore Roosevelt', 'Theodore Roosevelt', false, 100),
  (102, 'Franklin Roosevelt', 'Franklin Roosevelt', false, 101),
  (102, 'William Taft', 'William Taft', false, 102),
  (102, 'Warren Harding', 'Warren Harding', false, 103),
  (102, 'Calvin Coolidge', 'Calvin Coolidge', false, 104),
  (103, 'Germany invaded Poland', 'Đức xâm lược Ba Lan', false, 100),
  (103, 'To stop the spread of communism', 'Để ngăn chặn sự lây lan của chủ nghĩa cộng sản', false, 101),
  (103, 'Sinking of the Lusitania', 'Vụ chìm tàu Lusitania', false, 102),
  (103, 'To free Kuwait', 'Để giải phóng Kuwait', false, 103),
  (103, 'Germany attacked U.S. ships', 'Đức tấn công tàu Hoa Kỳ', false, 104),
  (104, 'Woodrow Wilson', 'Woodrow Wilson', false, 100),
  (104, 'Harry Truman', 'Harry Truman', false, 101),
  (104, 'Herbert Hoover', 'Herbert Hoover', false, 102),
  (104, 'Dwight Eisenhower', 'Dwight Eisenhower', false, 103),
  (104, 'Calvin Coolidge', 'Calvin Coolidge', false, 104),
  (105, 'Germany, Italy, and the Soviet Union', 'Đức, Ý, và Liên Xô', false, 100),
  (105, 'China, Japan, and Korea', 'Trung Quốc, Nhật Bản, và Hàn Quốc', false, 101),
  (105, 'Germany, Austria-Hungary, and Turkey', 'Đức, Áo-Hung, và Thổ Nhĩ Kỳ', false, 102),
  (105, 'Spain, Italy, and Japan', 'Tây Ban Nha, Ý, và Nhật Bản', false, 103),
  (105, 'Germany, Russia, and Japan', 'Đức, Nga, và Nhật Bản', false, 104),
  (106, 'World War I', 'Thế chiến thứ nhất', false, 100),
  (106, 'Korean War', 'Chiến tranh Triều Tiên', false, 101),
  (106, 'Vietnam War', 'Chiến tranh Việt Nam', false, 102),
  (106, 'Spanish-American War', 'Chiến tranh Tây Ban Nha-Mỹ', false, 103),
  (106, 'Civil War', 'Nội chiến', false, 104),
  (107, 'Terrorism', 'Khủng bố', false, 100),
  (107, 'Fascism', 'Chủ nghĩa phát xít', false, 101),
  (107, 'The Great Depression', 'Đại Suy thoái', false, 102),
  (107, 'Imperialism', 'Chủ nghĩa đế quốc', false, 103),
  (107, 'Slavery', 'Chế độ nô lệ', false, 104),
  (108, 'To free Korea from Japan', 'Để giải phóng Triều Tiên khỏi Nhật Bản', false, 100),
  (108, 'To gain new territory', 'Để có lãnh thổ mới', false, 101),
  (108, 'To support the United Nations only', 'Chỉ để hỗ trợ Liên Hợp Quốc', false, 102),
  (108, 'To stop terrorism', 'Để ngăn chặn khủng bố', false, 103),
  (108, 'To end slavery in Korea', 'Để chấm dứt chế độ nô lệ ở Triều Tiên', false, 104),
  (109, 'To support France against North Vietnam', 'Để hỗ trợ Pháp chống lại Bắc Việt', false, 100),
  (109, 'To gain new territory', 'Để có lãnh thổ mới', false, 101),
  (109, 'To stop terrorism', 'Để ngăn chặn khủng bố', false, 102),
  (109, 'To free Vietnam from Japan', 'Để giải phóng Việt Nam khỏi Nhật Bản', false, 103),
  (109, 'To enforce a United Nations treaty', 'Để thực thi một hiệp ước Liên Hợp Quốc', false, 104),
  (110, 'Ended the Cold War', 'Kết thúc Chiến tranh Lạnh', false, 100),
  (110, 'Gave women the right to vote', 'Cho phụ nữ quyền bỏ phiếu', false, 101),
  (110, 'Freed the slaves', 'Giải phóng nô lệ', false, 102),
  (110, 'Lowered the voting age to 18', 'Hạ độ tuổi bỏ phiếu xuống 18', false, 103),
  (110, 'Established Social Security', 'Thành lập An sinh Xã hội', false, 104),
  (111, 'Led the Underground Railroad', 'Lãnh đạo Đường sắt Ngầm', false, 100),
  (111, 'Was the first African American president', 'Là tổng thống người Mỹ gốc Phi đầu tiên', false, 101),
  (111, 'Wrote the 14th Amendment', 'Viết Tu chính án thứ 14', false, 102),
  (111, 'Founded the NAACP', 'Thành lập NAACP', false, 103),
  (111, 'Led the March to the Sea', 'Lãnh đạo cuộc Hành quân ra Biển', false, 104),
  (112, 'To stop the spread of communism', 'Để ngăn chặn sự lây lan của chủ nghĩa cộng sản', false, 100),
  (112, 'To respond to the September 11 attacks', 'Để đáp trả vụ tấn công 11 tháng 9', false, 101),
  (112, 'To remove Saddam Hussein from power', 'Để loại bỏ Saddam Hussein khỏi quyền lực', false, 102),
  (112, 'To free Iran from Iraq', 'Để giải phóng Iran khỏi Iraq', false, 103),
  (112, 'To enforce a no-fly zone', 'Để thực thi vùng cấm bay', false, 104),
  (113, 'The Pearl Harbor attack', 'Vụ tấn công Trân Châu Cảng', false, 100),
  (113, 'A nuclear missile crisis', 'Khủng hoảng tên lửa hạt nhân', false, 101),
  (113, 'A major hurricane struck New York', 'Một cơn bão lớn tấn công New York', false, 102),
  (113, 'The fall of the Berlin Wall', 'Sự sụp đổ của Bức tường Berlin', false, 103),
  (113, 'A school shooting in Washington, D.C.', 'Một vụ xả súng trường học ở Washington, D.C.', false, 104),
  (114, 'Korean War', 'Chiến tranh Triều Tiên', false, 100),
  (114, 'Vietnam War', 'Chiến tranh Việt Nam', false, 101),
  (114, 'Persian Gulf War', 'Chiến tranh vùng Vịnh Ba Tư', false, 102),
  (114, 'Cold War', 'Chiến tranh Lạnh', false, 103),
  (114, 'Bosnian War', 'Chiến tranh Bosnia', false, 104),
  (115, 'Aztec', 'Aztec', false, 100),
  (115, 'Maya', 'Maya', false, 101),
  (115, 'Inca', 'Inca', false, 102),
  (115, 'Mestizo', 'Mestizo', false, 103),
  (115, 'Olmec', 'Olmec', false, 104),
  (116, 'Colorado (River)', 'Sông Colorado', false, 100),
  (116, 'Hudson (River)', 'Sông Hudson', false, 101),
  (116, 'Rio Grande', 'Sông Rio Grande', false, 102),
  (116, 'Ohio (River)', 'Sông Ohio', false, 103),
  (116, 'Columbia (River)', 'Sông Columbia', false, 104),
  (117, 'Atlantic (Ocean)', '(Đại dương) Đại Tây Dương', false, 100),
  (117, 'Indian (Ocean)', '(Đại dương) Ấn Độ', false, 101),
  (117, 'Arctic (Ocean)', '(Đại dương) Bắc Băng Dương', false, 102),
  (117, 'Gulf of Mexico', 'Vịnh Mexico', false, 103),
  (117, 'Caribbean Sea', 'Biển Caribbean', false, 104),
  (118, 'Pacific (Ocean)', '(Đại dương) Thái Bình Dương', false, 100),
  (118, 'Indian (Ocean)', '(Đại dương) Ấn Độ', false, 101),
  (118, 'Arctic (Ocean)', '(Đại dương) Bắc Băng Dương', false, 102),
  (118, 'Gulf of Mexico', 'Vịnh Mexico', false, 103),
  (118, 'Caribbean Sea', 'Biển Caribbean', false, 104),
  (119, 'Hawaii', 'Hawaii', false, 100),
  (119, 'District of Columbia', 'Đặc khu Columbia', false, 101),
  (119, 'Alaska', 'Alaska', false, 102),
  (119, 'Cuba', 'Cuba', false, 103),
  (119, 'Panama Canal Zone', 'Vùng Kênh đào Panama', false, 104),
  (120, 'California', 'California', false, 100),
  (120, 'Texas', 'Texas', false, 101),
  (120, 'Arizona', 'Arizona', false, 102),
  (120, 'Massachusetts', 'Massachusetts', false, 103),
  (120, 'Wyoming', 'Wyoming', false, 104),
  (121, 'Nevada', 'Nevada', false, 100),
  (121, 'Utah', 'Utah', false, 101),
  (121, 'Louisiana', 'Louisiana', false, 102),
  (121, 'Colorado', 'Colorado', false, 103),
  (121, 'Oklahoma', 'Oklahoma', false, 104),
  (122, 'New York City', 'Thành phố New York', false, 100),
  (122, 'Philadelphia', 'Philadelphia', false, 101),
  (122, 'Boston', 'Boston', false, 102),
  (122, 'Los Angeles', 'Los Angeles', false, 103),
  (122, 'Chicago', 'Chicago', false, 104),
  (123, 'Washington, D.C.', 'Washington, D.C.', false, 100),
  (123, 'Boston Harbor', 'Cảng Boston', false, 101),
  (123, 'Philadelphia', 'Philadelphia', false, 102),
  (123, 'San Francisco Bay', 'Vịnh San Francisco', false, 103),
  (123, 'Chesapeake Bay', 'Vịnh Chesapeake', false, 104),
  (124, 'Because there are 13 founding fathers', 'Vì có 13 người cha lập quốc', false, 100),
  (124, 'Because there are 13 amendments in the Bill of Rights', 'Vì có 13 tu chính án trong Tuyên ngôn Nhân quyền', false, 101),
  (124, 'Because there are 13 federal departments', 'Vì có 13 bộ liên bang', false, 102),
  (124, 'Because there are 13 Supreme Court justices', 'Vì có 13 thẩm phán Tòa án Tối cao', false, 103),
  (124, 'Because the country was founded in 1813', 'Vì đất nước được thành lập năm 1813', false, 104),
  (125, 'Because there are 50 amendments to the Constitution', 'Vì có 50 tu chính án đối với Hiến pháp', false, 100),
  (125, 'Because there are 50 founding fathers', 'Vì có 50 người cha lập quốc', false, 101),
  (125, 'Because there are 50 federal departments', 'Vì có 50 bộ liên bang', false, 102),
  (125, 'Because the flag was adopted in 1850', 'Vì lá cờ được thông qua năm 1850', false, 103),
  (125, 'Because there are 50 senators', 'Vì có 50 thượng nghị sĩ', false, 104),
  (126, 'America the Beautiful', 'America the Beautiful', false, 100),
  (126, 'My Country, ''Tis of Thee', 'My Country, ''Tis of Thee', false, 101),
  (126, 'God Bless America', 'God Bless America', false, 102),
  (126, 'Yankee Doodle', 'Yankee Doodle', false, 103),
  (126, 'This Land Is Your Land', 'This Land Is Your Land', false, 104),
  (127, 'July 14', 'Ngày 14 tháng 7', false, 100),
  (127, 'June 14', 'Ngày 14 tháng 6', false, 101),
  (127, 'May 1', 'Ngày 1 tháng 5', false, 102),
  (127, 'September 17', 'Ngày 17 tháng 9', false, 103),
  (127, 'November 11', 'Ngày 11 tháng 11', false, 104),
  (128, 'New Year''s Day, Valentine''s Day, Christmas Day', 'Ngày đầu năm mới, Ngày Valentine, Ngày Giáng sinh', false, 100),
  (128, 'Thanksgiving Day, Halloween, Independence Day', 'Ngày Lễ Tạ ơn, Halloween, Ngày Quốc khánh', false, 101),
  (128, 'Memorial Day, Mother''s Day, Labor Day', 'Ngày Chiến sĩ Trận vong, Ngày của Mẹ, Ngày Lao động', false, 102),
  (128, 'Christmas Day, St. Patrick''s Day, New Year''s Day', 'Ngày Giáng sinh, Ngày Thánh Patrick, Ngày đầu năm mới', false, 103),
  (128, 'Veterans Day, Election Day, Thanksgiving Day', 'Ngày Cựu chiến binh, Ngày Bầu cử, Ngày Lễ Tạ ơn', false, 104);
