import { N400_QUESTIONS, N400_QUESTIONS_BY_ID, type N400Question, type N400CategoryKey } from './questions-data';
import { N400_DISTRACTORS } from './distractors-data';
import { STATES_BY_CODE, type StateCode } from './state-data';
import { REPS_BY_STATE, repForDistrict } from './reps-data';
import type { QuestionAttempt, QuizMode } from './storage';

// ── Audio paths (served from public/n400-audio/*) ──

export function questionAudioUrl(id: number): string {
  return `/n400-audio/civic_question/q${String(id).padStart(3, '0')}.mp3`;
}

export function answerAudioUrl(id: number): string | null {
  // Not every question has answer audio (124 of 128 files exist).
  // The frontend tries the URL; missing files fall back gracefully.
  return `/n400-audio/civic_answer/a${String(id).padStart(3, '0')}.mp3`;
}

export function whatMeanQuestionAudioUrl(num: number): string {
  return `/n400-audio/What_mean_questions/question/${num}.mp3`;
}

export function whatMeanAnswerAudioUrl(num: number): string {
  return `/n400-audio/What_mean_questions/answer/${num}.mp3`;
}

export function yesNoAudioUrl(num: number): string {
  return `/n400-audio/Yes_no_question/sound/${num}.mp3`;
}

export function writingAudioUrl(num: number): string {
  return `/n400-audio/Writing_questions/${num}.mp3`;
}

// File name → URL path slug. Source-of-truth filenames at
// public/n400-audio/State/<state>/{Senator voice,Governor}/<File>.mp3
// were generated by replacing any non-[a-zA-Z0-9-] character with `_`,
// so `J.B. Pritzker` → `J_B__Pritzker`, `Ben Ray Luján` → `Ben_Ray_Luj_n`,
// `Jenniffer González-Colón` → `Jenniffer_Gonz_lez-Col_n`. The earlier
// version only handled spaces and broke for any name with punctuation
// or diacritics.
function audioFileSlug(name: string): string {
  return name.replace(/[^a-zA-Z0-9-]/g, '_');
}

export function senatorAudioUrl(stateCode: StateCode, senator: string): string | null {
  const info = STATES_BY_CODE[stateCode];
  if (!info) return null;
  const file = audioFileSlug(senator) + '.mp3';
  return `/n400-audio/State/${encodeURIComponent(info.nameEn)}/Senator%20voice/${encodeURIComponent(file)}`;
}

export function governorAudioUrl(stateCode: StateCode): string | null {
  const info = STATES_BY_CODE[stateCode];
  if (!info) return null;
  const file = audioFileSlug(info.governor) + '.mp3';
  return `/n400-audio/State/${encodeURIComponent(info.nameEn)}/Governor/${encodeURIComponent(file)}`;
}

export function capitalAudioUrl(stateCode: StateCode): string | null {
  const info = STATES_BY_CODE[stateCode];
  if (!info || !info.capital) return null;
  return `/n400-audio/State/${encodeURIComponent(info.nameEn)}/Capital/capital-${stateCode}.mp3`;
}

export function representativeAudioUrl(
  stateCode: StateCode,
  districtNumber: number | null
): string | null {
  const rep = repForDistrict(stateCode, districtNumber);
  return rep?.audioUrl ?? null;
}

/**
 * Picks the right "answer audio" URL for any question.
 * For location-based questions (23, 29, 61, 62) it routes to the
 * senator / rep / governor / capital MP3s; for everything else it
 * falls back to the static a*.mp3 set.
 */
export function answerAudioUrlFor(
  question: N400Question,
  stateCode: StateCode,
  districtNumber: number | null
): string | null {
  if (question.id === 23) {
    const info = STATES_BY_CODE[stateCode];
    if (!info || info.senators.length === 0) return null;
    return senatorAudioUrl(stateCode, info.senators[0]);
  }
  if (question.id === 29) {
    return representativeAudioUrl(stateCode, districtNumber);
  }
  if (question.id === 61) return governorAudioUrl(stateCode);
  if (question.id === 62) return capitalAudioUrl(stateCode);
  return answerAudioUrl(question.id);
}

// ── Per-user correct answers for location-based questions ────────────────────

export function correctAnswersFor(
  question: N400Question,
  stateCode: StateCode,
  districtNumber: number | null = null
): { en: string; vi: string }[] {
  if (!question.isLocationBased) {
    return question.answersEn.map((en, i) => ({ en, vi: question.answersVi[i] ?? en }));
  }
  const info = STATES_BY_CODE[stateCode];
  if (!info) return [];

  // Q23: senators
  if (question.id === 23) {
    return info.senators.map((s) => ({ en: s, vi: s }));
  }
  // Q29: representative — district-specific. If district is unknown, fall back
  // to "any rep from the user's state" (USCIS accepts any current rep).
  if (question.id === 29) {
    const rep = repForDistrict(stateCode, districtNumber);
    if (rep) return [{ en: rep.name, vi: rep.name }];
    const reps = REPS_BY_STATE.get(stateCode) ?? [];
    return reps.map((r) => ({ en: r.name, vi: r.name }));
  }
  // Q61: governor
  if (question.id === 61) {
    return [{ en: info.governor, vi: info.governor }];
  }
  // Q62: capital
  if (question.id === 62 && info.capital) {
    return [{ en: info.capital, vi: info.capital }];
  }
  return [];
}

// ── Distractor sampling (deterministic enough; pure) ─────────────────────────

function hashSeed(seed: string | number): number {
  const s = String(seed);
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(a: number) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Normalize an answer for comparison: lowercase, drop parenthesis characters
 * and collapse whitespace. USCIS wraps optional words in parentheses
 * (e.g. "(Franklin) Roosevelt"), so without this a distractor like
 * "(Franklin) Roosevelt" would slip past the exact/overlap filters and appear
 * next to the correct answer "Franklin Roosevelt" — differing only by "()".
 */
function normalizeAnswer(s: string): string {
  return s
    .toLowerCase()
    .replace(/[()]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function shuffle<T>(arr: T[], seed: string | number): T[] {
  const rng = mulberry32(hashSeed(seed));
  const out = [...arr];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

export interface QuizOption {
  id: 'A' | 'B' | 'C' | 'D';
  en: string;
  vi: string;
  isCorrect: boolean;
}

const OPTION_IDS: QuizOption['id'][] = ['A', 'B', 'C', 'D'];

/**
 * Build 4 MCQ options for a question:
 *   1 randomly-picked correct answer + 3 distractors drawn from OTHER questions in the same category.
 * Deterministic given (questionId, seed). Filters out distractors that are textually similar to any
 * correct answer (case-insensitive substring match either way).
 */
export function buildOptions(
  question: N400Question,
  stateCode: StateCode,
  seed: string | number,
  districtNumber: number | null = null
): QuizOption[] {
  const correctList = correctAnswersFor(question, stateCode, districtNumber);
  // Fall back to question.answersEn if location-based has no resolution (e.g. Q29 in v1).
  const fallback = correctList.length === 0
    ? question.answersEn.map((en, i) => ({ en, vi: question.answersVi[i] ?? en }))
    : correctList;

  const rng = mulberry32(hashSeed(`${question.id}-${seed}`));
  const correct = fallback[Math.floor(rng() * fallback.length)] ?? { en: '—', vi: '—' };

  const correctSet = new Set(fallback.map((c) => normalizeAnswer(c.en)));
  const candidates: { en: string; vi: string }[] = [];

  // 1. Try manually authored static distractors for this question
  const staticList = N400_DISTRACTORS[question.id] || [];
  for (const d of staticList) {
    const enNorm = normalizeAnswer(d.en);
    if (correctSet.has(enNorm)) continue;
    // Filter clear semantic overlap
    let overlap = false;
    for (const c of correctSet) {
      if (c.length > 4 && enNorm.includes(c)) { overlap = true; break; }
      if (enNorm.length > 4 && c.includes(enNorm)) { overlap = true; break; }
    }
    if (overlap) continue;
    candidates.push({ en: d.en, vi: d.vi });
  }

  // 2. Fall back to other questions in the same category if we have fewer than 3 candidates
  if (candidates.length < 3) {
    for (const q of N400_QUESTIONS) {
      if (q.id === question.id) continue;
      if (q.category !== question.category) continue;
      // Skip location-based Q's: their static answersEn are user-specific
      // (e.g., Q23 senators, Q61 governor) or placeholder text (Q29), neither
      // of which makes sense as a distractor for unrelated questions.
      if (q.isLocationBased) continue;
      for (let i = 0; i < q.answersEn.length; i++) {
        const en = q.answersEn[i];
        const vi = q.answersVi[i] ?? en;
        const enNorm = normalizeAnswer(en);
        if (correctSet.has(enNorm)) continue;
        // Filter clear semantic overlap.
        let overlap = false;
        for (const c of correctSet) {
          if (c.length > 4 && enNorm.includes(c)) { overlap = true; break; }
          if (enNorm.length > 4 && c.includes(enNorm)) { overlap = true; break; }
        }
        if (overlap) continue;
        candidates.push({ en, vi });
      }
    }
  }

  // 3. Fall back further to other categories if still fewer than 3 candidates
  if (candidates.length < 3) {
    for (const q of N400_QUESTIONS) {
      if (q.id === question.id) continue;
      if (q.isLocationBased) continue;
      for (let i = 0; i < q.answersEn.length; i++) {
        const en = q.answersEn[i];
        const vi = q.answersVi[i] ?? en;
        if (correctSet.has(normalizeAnswer(en))) continue;
        candidates.push({ en, vi });
      }
    }
  }

  // Dedupe by en text.
  const seen = new Set<string>();
  const unique: { en: string; vi: string }[] = [];
  for (const c of candidates) {
    const k = normalizeAnswer(c.en);
    if (seen.has(k)) continue;
    seen.add(k);
    unique.push(c);
  }

  const shuffled = shuffle(unique, `${question.id}-d-${seed}`);
  const distractors = shuffled.slice(0, 3);

  const all = shuffle(
    [
      { ...correct, isCorrect: true },
      ...distractors.map((d) => ({ ...d, isCorrect: false })),
    ],
    `${question.id}-o-${seed}`
  );

  return all.map((opt, i) => ({
    id: OPTION_IDS[i],
    en: opt.en,
    vi: opt.vi,
    isCorrect: opt.isCorrect,
  }));
}

// ── Mock test selection ──────────────────────────────────────────────────────

export const MOCK_TEST_QUESTION_COUNT = 20;
export const MOCK_TEST_PASS_THRESHOLD = 12; // 12/20 USCIS rule

export function selectMockTestQuestions(seed: string | number): N400Question[] {
  // 20 random questions across all 128, no repeats.
  const ids = N400_QUESTIONS.map((q) => q.id);
  return shuffle(ids, `mock-${seed}`)
    .slice(0, MOCK_TEST_QUESTION_COUNT)
    .map((id) => N400_QUESTIONS_BY_ID.get(id)!)
    .filter(Boolean);
}

export function isPass(score: number): boolean {
  return score >= MOCK_TEST_PASS_THRESHOLD;
}

// ── Practice session selection ───────────────────────────────────────────────

export interface PracticePreset {
  id: 'quick' | 'standard' | 'deep' | 'full';
  titleVi: string;
  titleEn: string;
  descVi: string;
  count: number | null;   // null = all available questions
  minutes: number | null; // null = no time estimate shown
}

export const PRACTICE_PRESETS: PracticePreset[] = [
  { id: 'quick', titleVi: 'Ôn nhanh', titleEn: 'Quick Review', descVi: 'Ôn nhanh để làm mới trí nhớ.', count: 5, minutes: 3 },
  { id: 'standard', titleVi: 'Luyện hằng ngày', titleEn: 'Daily Practice', descVi: 'Bài luyện đề xuất cho hôm nay.', count: 10, minutes: 5 },
  { id: 'deep', titleVi: 'Thử thách', titleEn: 'Challenge', descVi: 'Thử thách bản thân và lên trình.', count: 20, minutes: 10 },
  { id: 'full', titleVi: 'Ôn toàn bộ', titleEn: 'Master Review', descVi: 'Ôn toàn bộ câu hỏi như thi thật.', count: null, minutes: 35 },
];

export function selectPracticeQuestionIds(
  seed: string | number,
  count: number | null,
  category: N400CategoryKey | null = null
): number[] {
  // Same shuffle key the practice page has always used, so "full" keeps
  // producing the identical order for an existing seed. Q29 is always
  // included: without a district, correctAnswersFor falls back to any
  // current representative of the user's state.
  const pool = category === null ? N400_QUESTIONS : N400_QUESTIONS.filter((q) => q.category === category);
  const ids = pool.map((q) => q.id);
  const shuffled = shuffle(ids, `practice-${seed}`);
  return count === null ? shuffled : shuffled.slice(0, Math.min(count, shuffled.length));
}

// ── Practice recommendation ──────────────────────────────────────────────────

const RECOMMENDATION_WINDOW = 10;     // look at the last N attempts per category
const RECOMMENDATION_MIN_ATTEMPTS = 5; // need enough signal before recommending
const RECOMMENDATION_MIN_WRONG = 3;    // only surface a genuine weak spot

export interface PracticeRecommendation {
  category: N400CategoryKey;
  wrongCount: number;
  sampleSize: number;
}

/**
 * Picks the user's single weakest category from their attempt history
 * (chronological order), or null when no category has enough recent misses
 * to justify a recommendation.
 */
export function recommendWeakCategory(
  attempts: readonly { questionId: number; wasCorrect: boolean }[]
): PracticeRecommendation | null {
  const byCategory = new Map<N400CategoryKey, boolean[]>();
  for (const a of attempts) {
    const q = N400_QUESTIONS_BY_ID.get(a.questionId);
    if (!q) continue;
    const list = byCategory.get(q.category) ?? [];
    list.push(a.wasCorrect);
    byCategory.set(q.category, list);
  }

  let best: PracticeRecommendation | null = null;
  let bestRate = 0;
  for (const [category, results] of byCategory) {
    if (results.length < RECOMMENDATION_MIN_ATTEMPTS) continue;
    const recent = results.slice(-RECOMMENDATION_WINDOW);
    const wrongCount = recent.filter((ok) => !ok).length;
    if (wrongCount < RECOMMENDATION_MIN_WRONG) continue;
    const rate = wrongCount / recent.length;
    if (rate > bestRate || (rate === bestRate && wrongCount > (best?.wrongCount ?? 0))) {
      best = { category, wrongCount, sampleSize: recent.length };
      bestRate = rate;
    }
  }
  return best;
}

// ── Review debt (graded modes only — spec D1) ────────────────────────────────

/**
 * Attempts that count toward review debt and weakness signals. Flashcard
 * self-grades are recognition, not retrieval: they neither create nor clear
 * wrong-answer debt.
 */
export function gradedOnly<T extends { mode: QuizMode }>(attempts: readonly T[]): T[] {
  return attempts.filter((a) => a.mode !== 'flashcard');
}

/**
 * Question ids whose LAST graded attempt was correct — the app's evidence of
 * "thuộc", and the same currency the mock test uses to decide pass/fail.
 *
 * Flashcard self-grades are excluded on purpose (spec D1, same rule as
 * gradedOnly above): tapping "Đã thuộc" while looking at the answer is
 * recognition, not retrieval, and would let a learner mark all 128 known in
 * two minutes. The flashcard deck's own marked-state is a different concept
 * and lives in `flashcardKnown`.
 */
export function masteredQuestionIds(attempts: readonly QuestionAttempt[]): number[] {
  const last = new Map<number, boolean>();
  for (const a of gradedOnly(attempts)) last.set(a.questionId, a.wasCorrect);
  return [...last.entries()].filter(([, ok]) => ok).map(([id]) => id);
}

/**
 * Question ids whose LAST graded attempt is wrong, most recently wrong first.
 * The single source of truth for "câu sai chưa ôn" — a later correct graded
 * attempt clears an id, a later wrong one re-opens it.
 */
export function lastWrongQuestionIds(attempts: readonly QuestionAttempt[]): number[] {
  const last = new Map<number, QuestionAttempt>();
  for (const a of attempts) {
    if (a.mode === 'flashcard') continue;
    last.set(a.questionId, a);
  }
  return [...last.values()]
    .filter((a) => !a.wasCorrect)
    .sort((x, y) => new Date(y.at).getTime() - new Date(x.at).getTime())
    .map((a) => a.questionId);
}

/**
 * Category with the most questions among `questionIds` (ties keep the first
 * category encountered). Feeds the "sai nhiều nhất ở chủ đề" insight on the
 * practice summary; null when the list is empty.
 */
export function mostMissedCategory(questionIds: readonly number[]): N400CategoryKey | null {
  const counts = new Map<N400CategoryKey, number>();
  for (const id of questionIds) {
    const q = N400_QUESTIONS_BY_ID.get(id);
    if (!q) continue;
    counts.set(q.category, (counts.get(q.category) ?? 0) + 1);
  }
  let best: N400CategoryKey | null = null;
  let bestCount = 0;
  for (const [category, n] of counts) {
    if (n > bestCount) {
      best = category;
      bestCount = n;
    }
  }
  return best;
}

/**
 * True when a question's correct answer is personal to the user but the app
 * cannot resolve it yet (Q29 needs the resolved congressional district).
 * Q23/Q61/Q62 only need stateCode, which always has a value.
 */
export function isPersonalizedAnswerUnavailable(
  question: N400Question,
  districtNumber: number | null
): boolean {
  return question.id === 29 && districtNumber === null;
}

// ── Flashcards filtering (shared by card view and list view) ─────────────────

export type FlashcardFilter = 'all' | 'unknown' | 'known' | 'bookmarks' | N400CategoryKey;

export function filterFlashcards(
  questions: N400Question[],
  filter: FlashcardFilter,
  bookmarks: number[],
  known: number[]
): N400Question[] {
  switch (filter) {
    case 'all':
      return questions;
    case 'unknown':
      return questions.filter((q) => !known.includes(q.id));
    case 'known':
      return questions.filter((q) => known.includes(q.id));
    case 'bookmarks':
      return questions.filter((q) => bookmarks.includes(q.id));
    default:
      return questions.filter((q) => q.category === filter);
  }
}
